### ISSUE TITLE
Connection to Seq using gelf refusing

### ISSUE THREAD

**Issue by Didza** [datalust/seq-input-gelf#123] opened 2023-07-13 07:59 UTC
Connection to Seq using gelf refusing all ports are opened workin on docker on window but not on ubuntu using linux containers. I have also tried http://trakvisa-seq:5341 and getting the same error.

```trakvisa-seq-input-gelf    |  ---> System.Net.Sockets.SocketException (111): Connection refused
trakvisa-seq-input-gelf    |    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
trakvisa-seq-input-gelf    |    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
trakvisa-seq-input-gelf    |    at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
trakvisa-seq-input-gelf    |    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
trakvisa-seq-input-gelf    |    --- End of inner exception stack trace ---
trakvisa-seq-input-gelf    |    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
trakvisa-seq-input-gelf    |    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
trakvisa-seq-input-gelf    |    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
trakvisa-seq-input-gelf    |    at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
trakvisa-seq-input-gelf    |    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
trakvisa-seq-input-gelf    |    at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
trakvisa-seq-input-gelf    |    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
trakvisa-seq-input-gelf    |    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
trakvisa-seq-input-gelf    |    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)```


services:
    trakvisa-seq:
      image: datalust/seq:latest
      container_name: trakvisa-seq
      restart: always
      environment:
        - ACCEPT_EULA=Y
      ports:
        - '5341:80'
      networks:
        - trakvisa-network
      volumes:
        - seq_data:/data
      logging:
        driver: "json-file"
        options:
          max-size: "50M"
          max-file: "10"
      deploy:
        resources:
          limits:
            cpus: '2'
            memory: 1G

    trakvisa-seq-input-gelf:
      image: datalust/seq-input-gelf:latest
      container_name: trakvisa-seq-input-gelf
      restart: always
      environment:
        SEQ_ADDRESS: "http://trakvisa-seq:80"
      depends_on:
        - trakvisa-seq
      ports:
        - "12201:12201/udp"
      networks:
        - trakvisa-network
      logging:
        driver: "json-file"
        options:
          max-size: "50M"
          max-file: "10"
      deploy:
        resources:
          limits:
            cpus: '2'
            memory: 1G
```

**Comment by nblumhardt** [comment] 2023-07-13 23:45
Hi - this is a duplicate of https://github.com/datalust/seq-tickets/discussions/1887, where there's some existing discussion/context. I'ts best we continue the discussion there (or please email our support address if you have a supported Seq subscription and would like this ticket tracked under it). Thanks!

**Closed by nblumhardt** 2023-07-13 23:45 UTC
